image:
  file: .gitpod.Dockerfile

tasks:
  # always start docker
  - command: sudo docker-up

  # main init & run
  - init: -|
      gcloud auth login \
        && ./service_account.sh \
        && make
    command: make run
